project:
  type: website

website:
  title: "Ismael Rosero - Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/IsmaelRRT/IsmaelRRT.github.io

  page-footer:
    border: true
    left: "Ismael_Rosero 2024©"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ismael-rosero-6260aa240

  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "Projects"
        menu:
          - text: "Netflix Data Dashboard (Tableau)"
            file: projects/netflix.qmd
          - text: "YouTube Trending (Tableau)"
            file: projects/youtube.qmd
          - text: "Orphanage Donations Consulting (R)"
            href: Consulting.html
          - text: "Crypto Markets Email Bot (Excel VBA)"
            file: projects/crypto_bot.qmd
          - text: "Bond Pricing & Yield Curve (Excel VBA)"
            file: projects/bond_model.qmd
          - text: "Sleep & Exercise vs Performance (R)"
            file: projects/sleep_exercise.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
